# Generated by Django 4.1.7 on 2023-03-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=512)),
                ('Answer', models.CharField(max_length=128)),
                ('Difficulty', models.CharField(max_length=16)),
            ],
        ),
    ]
