# Generated by Django 4.1.7 on 2023-03-07 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SetTutor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Questions',
        ),
    ]
