# Generated by Django 4.1.7 on 2023-03-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SetTutor', '0002_rename_question_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='Size',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
