# Generated by Django 4.1.7 on 2023-03-16 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SetTutor', '0006_questions_type_alter_questions_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='Answer',
        ),
    ]
